#!/bin/bash

# github : @mohamedboukerche22
# name : mohfetch


# Colors
RED="\e[31m"
GREEN="\e[32m"
BLUE="\e[34m"
CYAN="\e[36m"
WHITE="\e[97m"
RESET="\e[0m"


USER_HOST="${USER}@$(hostname)"
OS="$(grep PRETTY_NAME /etc/os-release | cut -d '"' -f2)"
KERNEL="$(uname -r)"
UPTIME="$(uptime -p)"
SHELL_NAME="$SHELL"
CPU="$(grep 'model name' /proc/cpuinfo | head -1 | cut -d ':' -f2 | sed 's/^ //')"
RAM="$(free -h | awk '/Mem:/ {print $3 "/" $2}')"


source /etc/os-release

DISTRO=$ID

# soon make it better 
case "$DISTRO" in
    ubuntu)
        LOGO="${YELLOW}
         _    
     ---(_)
 _/  ---  \\
(_) |   |
  \\  --- _/
     ---   
${RESET}"
        ;;

    arch)
        LOGO="${CYAN}
       /\\
      /  \\
     / /\\ \\
    / ____ \\
   /_/    \\_\\
${RESET}"
        ;;

    fedora)
        LOGO="${BLUE}
      ____  
     / __ \\
    / /_/ /
   / ____/
  /_/     
${RESET}"
        ;;

    debian)
        LOGO="${RED}
    _____
   /  __ \\
  |  /    |
  |  \\___-
   -____- 
${RESET}"
        ;;

    alpine)
        LOGO="${BLUE}
      /\\ /\\
     /  \\  \\
    /    \\  \\
   /      \\__\\
${RESET}"
        ;;

    *)
        LOGO="${WHITE}
   Linux
${RESET}"
        ;;
esac


printf "%b\n" \
"${LOGO}"
echo -e "${CYAN}$USER_HOST${RESET}"
echo -e "${BLUE}OS:${RESET}      $OS"
echo -e "${BLUE}Kernel:${RESET}  $KERNEL"
echo -e "${BLUE}Uptime:${RESET}  $UPTIME"
echo -e "${BLUE}Shell:${RESET}   $SHELL_NAME"
echo -e "${BLUE}CPU:${RESET}     $CPU"
echo -e "${BLUE}Memory:${RESET}  $RAM"
